{"uuid": "fdb602e8-8ede-448e-b044-fffb3f345f75", "children": ["34e7d212-8f3e-40f4-903f-a684c95e169c"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: Requested environment is not available\n\n", "trace": "  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\conftest.py\", line 42, in browser\n    browser = webdriver.Remote(\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1681760604134, "stop": 1681760604157}], "start": 1681760604134, "stop": 1681760604257}